# Generated by Django 5.0 on 2023-12-16 03:34

import api.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speakers', models.CharField(max_length=255)),
                ('banner', models.ImageField(upload_to=api.models.event_banner_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'tiff', 'svg'])])),
                ('description', models.TextField(max_length=2000)),
                ('event_type', models.CharField(choices=[('conference', 'Конференция'), ('hackathon', 'Хакатон'), ('webinar', 'Вебинар'), ('meetup', 'Митап'), ('lecture', 'Лекция'), ('exhibition', 'Выставка'), ('training', 'Тренинг'), ('discussion', 'Дискуссия'), ('forum', 'Форум'), ('job_opening', 'Вакансия'), ('certification', 'Сертификация'), ('testing', 'Тестирование'), ('internship', 'Стажировки')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('social_media_link', models.URLField(blank=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='events_participated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
