# DEV DOCKER
version: '2'

services:
  backend:
    restart: unless-stopped
    build:
      dockerfile: ./docker/backend/Dockerfile
      context: .
    image: backend:latest
    container_name: backend
    env_file:
      - .env
    # ports:
      # - "8000:8000"
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn -b 0.0.0.0:8000 backend.wsgi:application"
    volumes:
      - ./media:/backend/media:consistent
      - ./static:/backend/static:consistent
      - ./backend/backend/settings.py:/backend/backend/settings.py:consistent
    depends_on:
      - database
  database:
    restart: unless-stopped
    image: postgres:15
    container_name: database
    volumes:
      - ~/.pg/pg_data/devrel_hack:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - '1000:8080'
    depends_on:
      - database
  nginx:
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx_backend
    image: nginx_backend
    volumes:
      - ./static:/backend/static:consistent
      - ./media:/backend/media:consistent
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "${NGINX_EXTERNAL_PORT:-80}:80"