# Generated by Django 5.0 on 2023-12-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
