# Generated by Django 5.0 on 2023-12-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL тг'),
        ),
    ]
