# Generated by Django 5.0 on 2023-12-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_formfields'),
        ('users', '0003_user_telegram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events_participated', to='api.event', verbose_name='Мероприятия'),
        ),
    ]
